# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_ref', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='reportsapp.Device')),
            ],
        ),
    ]
